import React from 'react';

export default function PolicyPage() {
  return (
    <div className="container mt-5 mb-5" style={{ maxWidth: 800 }}>
      <h1 className="mb-4">SG&amp;m Insurance Coverage</h1>
      <p>This document outlines the comprehensive jewelry insurance coverage. By selecting this coverage at checkout, you confirm your understanding and agreement to the terms described herein. All protections and services outlined below are included under one unified policy. The pricing tier of your policy is automatically determined by SG&amp;m’s internal valuation software, which calculated coverage costs based on the insured item’s value, design complexity, rarity of materials and condition.</p>
      <p>SG&amp;m ensures that all insured jewelry is documented and registered in our Claims &amp; Verification Database. Each registered item is eligible for ongoing services and protection throughout the duration of an active policy term. You may elect either monthly or yearly subscription coverage based on your preferred service level and renewal cycle. Your policy includes access to inspections, maintenance, secure delivery options and repair or replacement services under verified condition.</p>
      <p>SG&amp;m provides scheduled maintenance by appointment, including professional polishing, prong tightening, gemstone resetting and authorized resizing of rings, necklaces, and bracelets, provided such resizing remains within structurally safe limits. Insured items shipped to and from SG&amp;m are eligible for expedited delivery services with optional secure packaging, tracking and signature verification. Additionally, clients may opt for temporary safekeeping services when traveling or relocating, subject to availability and custody terms.</p>
      <p>Clients may request laser encryption services, in which a micro-engraved code is embedded on the jewelry to confirm ownership and validate traceability. This service enhances recovery eligibility in the event of loss or theft. Laser encryption is offered as a value-add feature and included free of charge with certain yearly policy plans.</p>
      <p>If a gemstone becomes fractured, chipped, or otherwise damaged, SG&amp;m will conduct a formal assessment to determine whether the remaining gem material can be recut or reshaped while preserving the original design intent. When an exact restoration is not viable, SG&amp;m will offer the best possible redesign based on the salvaged materials and the current market value of the remaining gem weight. If no viable restoration can be achieved, replacement with a comparable design will be proposed.</p>
      <p>Loose gemstones of high market value, or the particular rarity, may require separate coverage and valuation from the surrounding metal or accent stones. Items such as Alexandrite, Paraiba Tourmaline may be irreplaceable in exact form. In such cases, SG&amp;m will replace with a gem of equal or greater market value based on the SG&amp;m Market Analyzer Claim Policy, though visual or compositional duplication cannot be guaranteed.</p>
      <p>SG&amp;m guarantees that all jewelry enrolled under a policy is inspected and verified to meet quality standards prior to coverage activation. SG&amp;m shall not be held liable for damages resulting from unauthorized repairs, negligent handling, or claims submitted without legal substantiation. This policy is designed to supplement your existing care practices.</p>
      <p>Obligation to limited premium coverage for home and other insurance policies that may qualify for your specific damaged properties you the customer are prioritizing to insure, with the items provided by the adjuster involved in the coverage within one standing policy available by your provider. The policy provided is an extension of the coverage of the limited warranty that is offered to new products that are not altered or damaged from the outstanding state of manufacturing, from distribution to markets. Items that are covered will be subjected to a new claim status, depending on the policy associated with SG&amp;m Market Analyzer data base of listed products, at any given jurisdiction of time a claim is established and or outstanding policy from one given user.</p>
      <p>This information is used to ensure damage of goods if not otherwise applicable to the market’s current prices of the properties and or materials that is being purchased by any SG&amp;m providers by using this application and or service all right reserved 2025.</p>
      <p>By selecting insurance during checkout, you acknowledge that you have truthfully represented the insured items details and condition to the best of your knowledge. You understand and accept the full terms of the SG&amp;m Jewelry Insurance Coverage. All disputes shall be subject to arbitration under the applicable legal jurisdiction governing SG&amp;m operations. All rights reserved 2025</p>
    </div>
  );
} 